# -*- coding: utf-8 -*-
"""superresolution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1spHKj9mnf4pf9kyNMKoHM5fMVH88MS7v
"""

import torchvision.datasets as datasets
from torchvision.transforms import ToTensor

"""Download train and validation dataset. We pre-processed train and validation dataset with super-resolution."""

train_data = datasets.WIDERFace(
    root = 'data',
    split = 'train',                         
    transform = ToTensor(), 
    download = True        
)
val_data = datasets.WIDERFace(
    root = 'data', 
    split = 'val', 
    transform = ToTensor(),
    download = True
)

print(train_data)
print(val_data)

val_data.img_info[0]

val_data.img_info[0]['img_path']

#val_data.parse_train_val_annotations_file()

val_data.img_info[0]

arr = val_data.img_info[3]['annotations']['blur'].numpy()
print(2 in arr)

"""Find blur == 2(heavy blur)"""

#return the indices of data_info with blur level == blur_level
def findBlur(data_info,blur_level):
  blur_list = []
  for i in range(len(data_info)):
    #print(data_info[i]['annotations']['blur'])
    if blur_level in data_info[i]['annotations']['blur'].numpy():
      blur_list.append(i)
  return blur_list

val_heavy_blur = findBlur(val_data.img_info,2)
print("heavy_blur size: " + str(len(val_heavy_blur)))
print("heavy/total: " + str(len(val_heavy_blur)/len(val_data.img_info)))

"""In the train data, there exist 8992 images contains heavy blur face, about 35% of the total train dataset. In the validation data, there exist 2328 images contains heavy blur face, about 36% of the total validation dataset. """

def imgName(path):
  return path[path.rindex('/')+1:]

print(imgName(val_data.img_info[0]['img_path']))

import shutil
import os


#put back the enhanced image to the origin path
def collectEnhancedFiles(data_info,blur_list,path):
  for index in blur_list:
    dst = data_info[index]['img_path']
    src = path + '/' + imgName(dst)
    shutil.copy(src,dst)

collectEnhancedFiles(val_data.img_info,val_heavy_blur,'./val_enhanced/final_resized')
